{
 "title": "Speedtest Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Ping and Jitter (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds",
     "legendFormat": "Ping (ms)"
    },
    {
     "expr": "speedtest_jitter_latency_milliseconds",
     "legendFormat": "Jitter (ms)"
    }
   ]
  },
  {
   "title": "Download Speed (Mbits/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "avg_over_time(speedtest_download_bits_per_second[$__interval]) * 10 ^ -6",
     "legendFormat": "Download Speed (Mbits/s)"
    }
   ]
  },
  {
   "title": "Upload Speed (Mbits/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "avg_over_time(speedtest_upload_bits_per_second[$__interval]) * 10 ^ -6",
     "legendFormat": "Upload Speed (Mbits/s)"
    }
   ]
  },
  {
   "title": "Current Download Test",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(speedtest_download_bits_per_second [30m])*10^-6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Upload Test",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(speedtest_upload_bits_per_second[30m])*10^-6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Speed Test Operational",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "36 hour MGDS (SLA)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(speedtest_download_bits_per_second[36h]) / count_over_time(speedtest_download_bits_per_second[36h])/ 570000000) * 100",
     "legendFormat": "Meets GMDS"
    }
   ]
  },
  {
   "title": "Current Ping",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(speedtest_ping_latency_milliseconds[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Jitter",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " last_over_time(speedtest_jitter_latency_milliseconds[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minimum Guaranteed Download Speed (SLA)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "avg_over_time(speedtest_download_bits_per_second[$__interval]) * 10 ^ -6",
     "legendFormat": "Mbps"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "avg_over_time(speedtest_download_bits_per_second[$__interval]) * 10 ^ -6",
     "legendFormat": "Mbps"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "avg_over_time(speedtest_upload_bits_per_second[$__interval]) * 10 ^ -6",
     "legendFormat": "Mbps"
    }
   ]
  }
 ]
}