apiVersion: v1
data:
  grafana.ini: W2F1dGguYW5vbnltb3VzXQplbmFibGVkID0gZmFsc2UKW2F1dGguYmFzaWNdCmVuYWJsZWQgPSBmYWxzZQpbc2VydmVyXQpyb290X3VybCA9IGh0dHA6Ly9zcGVlZC1ncmFmYW5hLjE5Mi4xNjguNTAuMjA4Lm5pcC5pbwpbc2Vzc2lvbl0KcHJvdmlkZXIgPSBtZW1vcnkKW3NtdHBdCmVuYWJsZWQgPSB0cnVlCmZyb21fYWRkcmVzcyA9IApmcm9tX25hbWUgPSBHcmFmYW5hIEFsZXJ0Cmhvc3QgPSBzbXRwLXNlcnZlci5tb25pdG9yaW5nLnN2YzoyNQpwYXNzd29yZCA9IApza2lwX3ZlcmlmeSA9IHRydWUKdXNlciA9IAo=
kind: Secret
metadata:
  name: grafana-config
  namespace: speed-tester
type: Opaque
