apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: speedtest-exporter
  name: speedtest-exporter
  namespace: speed-tester
spec:
  endpoints:
  - interval: 30m
    port: metrics
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
    scheme: http
    scrapeTimeout: 2m
  jobLabel: speedtest-exporter-exporter
  namespaceSelector:
    matchNames:
    - speed-tester
  selector:
    matchLabels:
      k8s-app: speedtest-exporter
